[package]
name = "bevy_prototype_lyon"
version = "0.1.0"
authors = ["Federico Rinaldi <gisquerin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.3"
lyon = "0.16.0"